language: python
os: linux
dist: xenial
branches:
  only:
  - master
install:
- pip install -r build-requirements.txt
- python setup.py install
script:
- pip install -r requirements.txt
- pytest tests