language: python
os: linux
dist: xenial
deploy:
  provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"
  distributions: "sdist"
  skip_existing: true
branches:
  only:
  - master
install:
- python setup.py install
script:
- pip install -r requirements.txt
- pytest tests