language: python
os: linux
dist: xenial
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJGU1MzUxYzY3LTRiNTItNDNkMC05NDdjLTEwYTk5ODRmZWUyMgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgHmVZIFr5l_bXk1qGNLHWoafSrNzN71XWpEBjjOwh-yE"
  distributions: "sdist"
  skip_existing: true
branches:
  only:
  - master
install:
- pip install -r build-requirements.txt
- python setup.py install
script:
- pip install -r requirements.txt
- pytest tests